export default function(){
    this.transition(
        this.fromRoute('index'),
        this.toRoute('about'),
        this.toRoute('proj'),
        this.use('toLeft'),
        this.reverse('toRight')
    );
    this.transition(
        this.fromRoute('about'),
        this.use('toLeft'),
        this.reverse('toRight')
    );
    this.transition(
        this.fromRoute('proj'),
        this.toRoute('about'),
        this.use('toLeft'),
        this.reverse('toRight')
    );
    this.transition(
        this.fromRoute('proj'),
        this.toRoute('single'),
        this.use('toDown'),
        this.reverse('toUp')
    );
}
